### ISSUE TITLE
Use in java source

### ISSUE THREAD

**Issue by d3rt0xx** [supersu-man/GitHubAPKUpdater-Library#1]
Hey dude,

very nice project.
Is it possible to use this in java? My project is written in java, not in kotlin.

I dont know how to use

"thread {
    val updater = Updater(this, "Link_to_your_repo")
    checkForUpdates(updater)
}"

in java

**Comment by supersu-man** [comment]
> Hey dude,
> 
> very nice project. Is it possible to use this in java? My project is written in java, not in kotlin.
> 
> I dont know how to use
> 
> "thread { val updater = Updater(this, "Link_to_your_repo") checkForUpdates(updater) }"
> 
> in java

[This](https://www.w3schools.com/java/java_threads.asp) article from w3schools should help you on usage of threads.

**Comment by d3rt0xx** [comment]
Thanks for fast answer. Any chance you can "translate" your code snippets to plain java?
